service: imap-email-server

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    # TODO: Add your AI API key here
    GEMINI_API_KEY: ${env:GEMINI_API_KEY, 'AIzaSyCYot_GC3mx1yIi3RPmkLcwVghls5t9Yqo'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
    lambdaPort: 8001
    noPrependStageInUrl: true

build:
  esbuild: true

functions:
  api:
    handler: dist/enhancedHandler.enhancedHandler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  exclude:
    - node_modules/**
    - src/test/**
    - coverage/**
    - .git/**
    - .vscode/**
    - ui/**
    - README.md
    - .eslintrc.js
    - jest.config.js 