service: imap-email-server

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY, 'AIzaSyCYot_GC3mx1yIi3RPmkLcwVghls5t9Yqo'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  patterns:
    - '!src/**'
    - '!tests/**'
    - '!coverage/**'
    - '!.git/**'
    - '!.cursor/**'
    - '!.vscode/**'
    - '!../ui/**'
    - '!*.md'
    - '!jest.config.js'
    - '!eslint.config.js'
    - '!tsconfig.json'
    - '!webpack.config.js'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'
    - 'package-lock.json'
